### PR TITLE
Fix missing import in gtk/window.rs

### PR DESCRIPTION
**Pull request by klemensn**
Cherry-picked from jpochyla/druid@a9522f5 .

Otherwise building jpochyla/psst on Linux or OpenBSD fails:
```
error[E0433]: failed to resolve: use of undeclared type `XcbHandle`
   --> /home/kn/src/druid/druid-shell/src/backend/gtk/window.rs:118:30
    |
118 |         RawWindowHandle::Xcb(XcbHandle::empty())
    |                              ^^^^^^^^^ not found in this scope
    |
```

This code was introduced in 2da53f040625b57e3e7741ceba1d261e19b07359 which
seems to target Windows and Mac but not Linux, so I assume that is why it
went unnoticed.

### CODE REVIEW

**Review by Maan2003 — APPROVED** [review]
Thanks! I think CI doesnot test with raw-win-handle feature

**Comment by klemensn** [comment]
Pardon the noise, I meant put this comment https://github.com/linebender/druid/pull/1993#issuecomment-967223703 here.
